on: [ push ]

name: CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      # Init compilers
      - run: ./gradlew clean --scan
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cbindgen --force
        working-directory: untitled
      - run: cargo install bindgen --force
        working-directory: untitled

      # Compile first pass
      - run: ./gradlew assemble --scan
        continue-on-error: true
      - run: cargo build --all --all-targets
        working-directory: untitled
        continue-on-error: true

      # Compile second pass
      - run: ./gradlew assemble --scan
      - run: cargo build --all --all-targets
        working-directory: untitled
